version: '3.8'

services:
  db:
    image: mysql 
    container_name: mysql_db
    restart: always 
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: my_db 
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - ./db-data:/var/lib/mysql
      - ./db-logs:/var/log/mysql
    ports:
      - '3306:3306'

  app:
    container_name: my_app 
    build:
      context: ./php
    ports:
      - '8080:80'
    volumes:
      - ./src:/app
    depends_on:
      - db

  nginx:
    image: nginx
    container_name: nginx_server
    ports:
      - '8083:80'
    volumes:
      - ./src:/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
