version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: laravel_docker
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  server:
    container_name: server
    build:
      context: ./php
    ports:
      - '8080:80'
    volumes:
      - ./src:/var/www/laravel_docker
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - db

